<?php
/**
 * Implementation of hook_perm()
 */
function http_reject_perm() {
  return array('administer http_reject');
}

/**
 * Implementation of hook_menu()
 */
function http_reject_menu() {
  $items['admin/settings/http_reject'] = array(
    'title' => t('HTTP Redirect'),
    'decription' => t('Configure HTTP Redirect settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('http_reject_admin_page'),
    'access arguments' => array('administer http_reject'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'http_reject.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_boot()
 *
 * Look at the request and see if it needs to be rejected.
 */
function http_request_boot() {

}
